import json
import os
from pathlib import Path

from dotenv import load_dotenv
from groq import Groq


KEYWORDS_FILE = Path("keywords_output.json")
BLOG_FILE = Path("final_blog.md")
MODEL = "openai/gpt-oss-120b"


def load_keywords(filename):
    with filename.open("r", encoding="utf-8") as file:
        keyword_chunks = json.load(file)

    keywords = []
    seen = set()

    for chunk in keyword_chunks:
        for item in chunk.get("keywords", []):
            keyword = item.get("keyword", "").strip()
            if keyword and keyword.lower() not in seen:
                keywords.append(item)
                seen.add(keyword.lower())

    if not keywords:
        raise ValueError(f"No keywords found in {filename}")

    return keywords


def create_blog_prompt(keywords):
    keyword_lines = "\n".join(
        f"- {item['keyword']} ({item.get('importance', 'medium')}): "
        f"{item.get('reason', '')}"
        for item in keywords
    )

    return f"""You are an expert educational blog writer and SEO editor.

Write a clear, useful, original educational blog using only the supplied
keywords and their context. Do not invent statistics, claims, student
outcomes, or technical details that are not supported by the keyword list.

Requirements:
- Return Markdown only.
- Begin with an engaging, specific title.
- Use an introduction, descriptive H2 sections, and a concise conclusion.
- Explain concepts for beginners without removing important technical meaning.
- Use the high-importance keywords naturally in headings or body text.
- Avoid keyword stuffing, repeated phrases, and references to this prompt.
- Do not mention that the blog was generated by an LLM.
- Target approximately 900-1200 words.

Keyword source:
{keyword_lines}
"""


def generate_blog(client, keywords):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {
                "role": "system",
                "content": "You write accurate, readable educational blogs.",
            },
            {"role": "user", "content": create_blog_prompt(keywords)},
        ],
        temperature=0.5,
    )

    blog = response.choices[0].message.content
    if not blog:
        raise ValueError("The LLM returned an empty blog")

    return blog.strip()


def main():
    load_dotenv()
    api_key = ""
    if not api_key:
        raise ValueError("GROQ_API_KEY was not found in the environment or .env")

    keywords = load_keywords(KEYWORDS_FILE)
    print(f"Loaded {len(keywords)} unique keywords.")

    client = Groq(api_key=api_key)
    blog = generate_blog(client, keywords)

    BLOG_FILE.write_text(blog + "\n", encoding="utf-8")
    print(f"Blog saved to: {BLOG_FILE}")


if __name__ == "__main__":
    main()